### PR TITLE
fix(item-update): convert ObjectId to string before using it as criteria

### PR DESCRIPTION
**Pull request by jankal**

### CODE REVIEW

**Review by pauloamgomes — COMMENTED** [review]
Hey @jankal , not sure about the change, if we cast it to string the criteria seems not valid, for updates it should exclude the current id and (at least with MongoDB) its not excluding anymore.

**Comment by jankal** [comment]
@pauloamgomes It seems that we will need to differentiate between MongoDB and the SQLite implementation here. I made my changes because the raw object (not string) caused an Exception because `ObjectID->__set_state()` is not defined (the SQLite implementation seems to use var_export here).

**Comment by pauloamgomes** [comment]
Yeah, I was afraid that the issue would be on sqlite... can you update your fix in way it works for both cases?

**Comment by jankal** [comment]
@pauloamgomes I just added a commit which removes Mongo specific objects entirely. Could you please review/check it?

**Comment by pauloamgomes** [comment]
Seems to not cover all situations, try the following test:

1. Create entry with title test123
2. Create another entry with same title (ok - insert - it creates as test123-1)
3. Clear the slug field and save again (nok - update - it creates as test123-2, but should be test123-1)
3. Clear the slug field and save again (nok - update - it creates as test123 but should be test123-1)

During the tests also found a possible infinite loop.

That was the reason that I used the regex criteria, otherwise it could be quite tricky to have the right slug numbering.

**Comment by pauloamgomes** [comment]
Hey @jankal , fixed that by handling the mongodb/sqlite checks separately

**Comment by jankal** [comment]
@pauloamgomes Thanks for doing this! I was just to busy this week. I will check wether your fixes work when I get home.

**Pull request closed without merging**
