### PR TITLE
Composer installation

### PR DESCRIPTION
**Pull request by Raruto**
Hi Paulo,

by chance, could you publish this library also on [packagist.org](https://packagist.org/packages/pauloamgomes/)? 

---

**List of changes:**

- added alternative installation instructions (as proposed by [piotr-cz](https://github.com/composer/installers/pull/284))
- renamed "`Cockpit\\BetterSlugs\\Utils`" to "`BetterSlugs\\Helper\\Utils`") in order to take advantage of cockpit's inbuilt autoloader (ref. [`$app->loadModules`](https://github.com/agentejo/cockpit/blob/3ff29727a7a86f7c1f8726cea41e0c9dbfe93cf7/bootstrap.php#L275)) and removed unnecessary composer "classmap" autoloader dependency 
- added some PHP Docs

---

_Have a nice day,
Raruto_

### CODE REVIEW

**Comment by pauloamgomes** [comment]
Thanks! Is available now in `pauloamgomes/cockpitcms-betterslugs`

**Comment by Raruto** [comment]
Thank you,
one last bore, could you also draft a first [release](https://github.com/pauloamgomes/CockpitCMS-BetterSlugs/releases) here on github? Just to avoid using the "`dev-master`" branch:

```gh
composer require pauloamgomes/cockpitcms-betterslugs:dev-master
```

[Here](https://packagist.org/about) you can find some information on how packagist.org updates its database.

_Thanks in advance,
Raruto_


---

**PS** if that's okay with you, in the next few days I'll try to send similar pulls to a couple of your other useful addons..

**Comment by pauloamgomes** [comment]
Sounds fine! I'm a bit busy, but happy to review and merge any PRs.

**Comment by Raruto** [comment]
Hi paulo,
don't worry there's no rush, I am in the process of creating a simple quick start boilerplate that can guarantee a minimum version control of installed [addons](https://github.com/Raruto/cockpit-blog#cockpit-addons).

**Pull request merged**
